### ISSUE TITLE
Ability to add custom words

### ISSUE THREAD

**Issue by hashhar** [dg9ngf/TodoHighlighter#2]
The way that we can add custom keywords to the task list in Visual Studio, we should be able to add custom words to be highlighted.

I would like to work on this feature.

**Comment by ygoe** [comment]
Thank you for your interest. Have you developed Visual Studio extensions before? If you know how to do this (see #1 for a hint to possibly similar code) I'd be happy to review your suggestion. I'm not working on that feature now or in the near future.

**Comment by jpozo20** [comment]
I'm also learning to code Visual Studio extensions, currently working on a TODO manager. I'll be checking this and the other issues out on the weekend. ✌🏼
