### ISSUE TITLE
Update support for newer VS version

### ISSUE THREAD

**Issue by m1lhaus** [dg9ngf/TodoHighlighter#5]
Hello,
this extensions is long time not updated. I forked the extension and updated it to work with latest Visual Studio 2017 awhile ago. I am planning to update it to work also with VS2019. Is it worth the effort to even ask for a pull request? Or is it already abandoned project?

**Comment by ygoe** [comment]
This extension has been replaced by https://marketplace.visualstudio.com/items?itemName=ygoe.SelectionTodoHighlighter

**Comment by m1lhaus** [comment]
Works like a charm. Thx
